version: '3.9'
services:
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3001:3001

  openapi_generator:
    build:
      context: ./tools/openapi-generator
      dockerfile: Dockerfile
    depends_on:
      - nestjs
    volumes:
      - ./tools/openapi-generator/.build:/local/out
    environment:
      - WAIT_HOSTS=nestjs:3001
